name: dialyzer
on: push

jobs:
  run-dialyzer:
    name: Run dialyzer
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.12.0'
        otp-version: '24.0'
    - name: Install dependencies
      run: mix deps.get
    - name: Check compiler warnings
      run: mix compile --warnings-as-errors
    - name: Run dialyzer
      run: mix dialyzer
