name: driver-tests
on: push

jobs:
  run-tests:
    name: Run driver tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        driver:
          - docker
          - local
          - ssh
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.12.0'
        otp-version: '24.0'
    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    # NOTE: Only needed for the SSH test but we'll setup some SSH things here
    # as well.
    - name: Configure ssh keys
      run: ssh-keygen -q -t ed25519 -N "" -f ~/.ssh/id_ed25519
    - name: Configure authorized keys
      run: cat ~/.ssh/id_ed25519.pub  > ~/.ssh/authorized_keys
    - name: Configure ssh host key
      run: ssh-keyscan localhost > ~/.ssh/known_hosts
    - name: Configure home permissions
      run: chmod 755 ~
    - name: Configure file permissions
      run: chmod 600 ~/.ssh/*
    # NOTE: to ensure the Elixir/Node binaries are found when using SSH
    # we need to set the path for our ssh session, this is a simple hacky way
    # to accomplish that.
    - name: Save environment (PATH)
      run: echo PATH="$PATH" | sudo tee /etc/environment
    - name: Run tests for ${{ matrix.driver }} driver
      run: ./bin/test_driver.sh ${{ matrix.driver }}
