name: driver-tests
on: push

jobs:
  run-tests:
    name: Run driver tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        driver:
          - docker
          - local
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.12.0'
        otp-version: '24.0'
    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Run tests for ${{ matrix.driver }} driver
      run: ./bin/test_driver.sh ${{ matrix.driver }}
