name: tests
on: push

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      AWS_ACCESS_KEY: '${{ secrets.AWS_ACCESS_KEY }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.12.0'
        otp-version: '24.0'
    - name: Install dependencies
      run: mix deps.get
    - name: Check compiler warnings
      run: mix compile --warnings-as-errors
    - name: Run tests
      run: mix test --trace
